# syntax=docker/dockerfile:1.7-labs
FROM node:20-alpine

WORKDIR /app
RUN apk update
RUN apk add --no-cache libc6-compat
RUN npm i -g corepack@latest
RUN corepack enable pnpm
ENV NEXT_TELEMETRY_DISABLED=1
